#!/bin/bash
cd /home/isa37/git/lab2/sim/
source /software/scripts/init_msim6.2g
rm -r work
vlib work
vcom -93 -work ./work ../src/multiplier/FF.vhd
vcom -93 -work ./work ../src/common/fpnormalize_fpnormalize.vhd
vcom -93 -work ./work ../src/common/fpround_fpround.vhd
vcom -93 -work ./work ../src/common/packfp_packfp.vhd
vcom -93 -work ./work ../src/common/unpackfp_unpackfp.vhd
vcom -93 -work ./work ../src/mbe/my_pkg.vhd
vcom -93 -work ./work ../src/mbe/partial_product_generator.vhd
vcom -93 -work ./work ../src/mbe/s_padder.vhd
vcom -93 -work ./work ../src/mbe/FA.vhd
vcom -93 -work ./work ../src/mbe/HA.vhd
vcom -93 -work ./work ../src/mbe/dadda_stage1.vhd
vcom -93 -work ./work ../src/mbe/dadda_stage2.vhd
vcom -93 -work ./work ../src/mbe/dadda_stage3.vhd
vcom -93 -work ./work ../src/mbe/dadda_stage4.vhd
vcom -93 -work ./work ../src/mbe/dadda_stage5.vhd
vcom -93 -work ./work ../src/mbe/dadda_stage6.vhd
vcom -93 -work ./work ../src/mbe/rca63.vhd
vcom -93 -work ./work ../src/mbe/dadda_tree.vhd
vcom -93 -work ./work ../src/mbe/mbe.vhd
vcom -93 -work ./work ../src/multiplier/fpmul_stage1_struct.vhd
vcom -93 -work ./work ../src/multiplier/fpmul_stage2_struct.vhd
vcom -93 -work ./work ../src/multiplier/fpmul_stage3_struct.vhd
vcom -93 -work ./work ../src/multiplier/fpmul_stage4_struct.vhd
vcom -93 -work ./work ../src/multiplier/fpmul_pipeline.vhd
vcom -93 -work ./work ../src/multiplier/REG.vhd
vcom -93 -work ./work ../src/multiplier/fpmul_pipeline_inputRegistered.vhd

vcom -93 -work ./work ../tb/clk_gen.vhd
vcom -93 -work ./work ../tb/tb_output_data_checker.vhd
vcom -93 -work ./work ../tb/data_maker.vhd


vlog -work ./work ../tb/TB_MULT.v

vsim work.tb_mult

